- name: install package
  yum:
    name: cockpit-docker
    state: present
  become: yes

- name: restart service
  service:
    name: cockpit.socket
    state: restarted
    enabled: yes
  become: yes