- hosts: all
  tasks:
    - include_role:
        name: os_updates
    - include_role:
        name: kernel_config
    - include_role:
        name: cockpit
        tasks_from: cockpit
    - include_role:
        name: docker
    - include_role:
        name: cockpit
        tasks_from: cockpit-docker