- name: install pyaml deps
  yum:
    name: "{{pyaml_deps}}"
    state: present
  become: yes

- name: upgrade setuptools
  pip:
    name: setuptools
    state: latest

- name: install k8s_raw dependencies
  pip:
    name: "{{item}}"
    state: present
  become: yes
  with_items:
    - openshift
    - pyaml