- name: install pyaml deps
  yum:
    name: gcc
    state: present
  become: yes

- name: install k8s_raw dependencies
  pip:
    name: "{{item}}"
    state: present
  with_items:
    - openshift
    - pyaml