- name: source keystonerc
  shell: . ~/keystonerc
  args:
    chdir: "{{ansible_env.HOME}}"

- name: get image id
  shell: openstack image list -f value -c ID
  args:
    chdir: "{{ansible_env.HOME}}"
  register: image_id

- name: create os keypair
  os_keypair:
      cloud: "{{ansible_env.OS_PROJECT_NAME}}"
      state: present
      name: "{{ansible_key}}"
      public_key_file: "{{os_pubkey}}"

- name: launch instance
  os_server:
      state: present
      auth:
        auth_url: "{{ansible_env.OS_AUTH_URL}}"
        username: "{{ansible_env.OS_USERNAME}}"
        password: "{{ansible_env.OS_PASSWORD}}"
        project_name: "{{ansible_env.OS_PROJECT_NAME}}"
      name: plex-live
      image: "{{image_id.stdout}}"
      key_name: "{{ansible_key}}"
      timeout: 200
      flavor: 6
      nics:
        - net-id: 34605f38-e52a-25d2-b6ec-754a13ffb723
        - net-name: another_network
      meta:
        hostname: plex.magiccityit.com
        group: plex